apiVersion: v1
kind: ServiceAccount
metadata:
  name: vmkube-watch-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vmkube-watch-cr
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs: ["get", "list", "watch"]
  - nonResourceURLs:
    - '*'
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vmkube-watch-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmkube-watch-cr
subjects:
- kind: ServiceAccount
  name: vmkube-watch-sa
###
# Modify the namespace
###
  namespace: vmkube-watch
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vmkube-watch-deployment
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: vmkube-watch
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vmkube-watch
        version: v1
    spec:
      containers:
      - env:
        - name: INCLUSTER_CONFIG
          value: "1"      
        - name: GROUPANDVERSION
          valueFrom:
            configMapKeyRef:
              name: vmkube-watch-cm
              key: groupversion
        - name: RESOURCETYPE
          valueFrom:
            configMapKeyRef:
              name: vmkube-watch-cm
              key: resourcetype
        - name: NAMESPACE
          valueFrom:
            configMapKeyRef:
              name: vmkube-watch-cm
              key: namespace
        image: us-central1-docker.pkg.dev/navneet-410819/whoami6443-hub/whoami6443/vmkube-watch:0.1.2
        imagePullPolicy: Always
        name: vmkube-watch
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 64Mi
        securityContext:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
          runAsNonRoot: true
          runAsUser: 10001
        volumeMounts:
        - mountPath: /app/deleted
          name: config-volume-deleted
        - mountPath: /app/modified
          name: config-volume-modified
        - mountPath: /app/added
          name: config-volume-added
        - mountPath: /user/appuser
          name: cache-volume
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        stdin: true
        tty: true
      volumes:
      - name: config-volume-deleted
        configMap:
          name: vmkube-watch-cm
          defaultMode: 0755
          items:
          - key: deleted1.sh
            path: deleted1.sh     
      - name: config-volume-modified
        configMap:
          name: vmkube-watch-cm
          defaultMode: 0755
          items:
          - key: mod1.sh
            path: mod1.sh     
      - name: config-volume-added
        configMap:
          name: vmkube-watch-cm
          defaultMode: 0755
          items:
          - key: added1.sh
            path: added1.sh     
      - name: cache-volume
        emptyDir: {}
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: vmkube-watch-sa
      serviceAccountName: vmkube-watch-sa
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vmkube-watch-cm
data:
  groupversion: "v1"
  resourcetype: "services"
  namespace: ""
  deleted1.sh: |
    #!/bin/bash    
    echo "$CHANGED_VARIABLE"|jq -r
    echo "delete function"
  mod1.sh: |
    #!/bin/bash
    echo "$CHANGED_VARIABLE"|jq -r
    echo "mod function 1"
  added1.sh: |
    #!/bin/bash
    echo "$CHANGED_VARIABLE"|jq -r
    echo "add function"  
